"use strict";
const electron = require("electron");
electron.contextBridge.exposeInMainWorld("electronAPI", {
  createTournament: (data) => electron.ipcRenderer.invoke("create-tournament", data),
  listTournaments: () => electron.ipcRenderer.invoke("list-tournaments"),
  startTournament: (id) => electron.ipcRenderer.invoke("start-tournament", id),
  exportTournament: (id) => electron.ipcRenderer.invoke("export-tournament", id),
  importTournament: (data) => electron.ipcRenderer.invoke("import-tournament", data),
  importTournamentOverwrite: (data) => electron.ipcRenderer.invoke("import-tournament-overwrite", data),
  getActiveTournament: () => electron.ipcRenderer.invoke("get-active-tournament"),
  updateTournament: (data) => electron.ipcRenderer.invoke("update-tournament", data),
  deleteTournament: (id) => electron.ipcRenderer.invoke("delete-tournament", id),
  readFile: (path) => electron.ipcRenderer.invoke("read-file", path),
  loadAthletes: () => electron.ipcRenderer.invoke("load-athletes"),
  saveAthlete: (athlete) => electron.ipcRenderer.invoke("save-athlete", athlete),
  updateAthlete: (athlete) => electron.ipcRenderer.invoke("update-athlete", athlete),
  deleteAthlete: (id) => electron.ipcRenderer.invoke("delete-athlete", id),
  deleteAthletes: (ids) => electron.ipcRenderer.invoke("delete-athletes", ids),
  importAthletes: () => electron.ipcRenderer.invoke("import-athletes"),
  exportAthletes: () => electron.ipcRenderer.invoke("export-athletes"),
  saveArbitro: (data) => electron.ipcRenderer.invoke("save-arbitro", data),
  updateArbitro: (data) => electron.ipcRenderer.invoke("update-arbitro", data),
  deleteArbitro: (arbitroId) => electron.ipcRenderer.invoke("delete-arbitro", arbitroId),
  deleteArbitros: (arbitroIds) => electron.ipcRenderer.invoke("delete-arbitros", arbitroIds),
  loadArbitros: () => electron.ipcRenderer.invoke("load-arbitros"),
  importArbitros: () => electron.ipcRenderer.invoke("import-arbitros"),
  exportArbitros: () => electron.ipcRenderer.invoke("export-arbitros"),
  gerarTodasChaves: (maxAtletas) => electron.ipcRenderer.invoke("gerar-todas-chaves", maxAtletas),
  gerarChave: (data) => electron.ipcRenderer.invoke("gerar-chave", data),
  loadChaves: () => electron.ipcRenderer.invoke("load-chaves"),
  loadChavePorCategoria: (categoriaId) => electron.ipcRenderer.invoke("load-chave-por-categoria", categoriaId),
  randomizarChave: (data) => electron.ipcRenderer.invoke("randomizar-chave", data),
  atribuirArbitroChave: (data) => electron.ipcRenderer.invoke("atribuir-arbitro-chave", data),
  importChaves: () => electron.ipcRenderer.invoke("import-chaves"),
  exportChaves: () => electron.ipcRenderer.invoke("export-chaves"),
  loadAreas: () => electron.ipcRenderer.invoke("load-areas"),
  saveArea: (data) => electron.ipcRenderer.invoke("save-area", data),
  updateArea: (data) => electron.ipcRenderer.invoke("update-area", data),
  deleteArea: (areaId) => electron.ipcRenderer.invoke("delete-area", areaId),
  deleteAreas: (areaIds) => electron.ipcRenderer.invoke("delete-areas", areaIds),
  loadChavesPorArea: (areaId) => electron.ipcRenderer.invoke("load-chaves-por-area", areaId),
  registrarResultado: (data) => electron.ipcRenderer.invoke("registrar-resultado", data),
  loadLutasCasadasPorArea: (areaId) => electron.ipcRenderer.invoke("load-lutas-casadas-por-area", areaId),
  saveLutaCasada: (data) => electron.ipcRenderer.invoke("save-luta-casada", data),
  updateLutaCasada: (data) => electron.ipcRenderer.invoke("update-luta-casada", data),
  deleteLutaCasada: (lutaCasadaId) => electron.ipcRenderer.invoke("delete-luta-casada", lutaCasadaId)
});
electron.contextBridge.exposeInMainWorld("activation", {
  check: () => electron.ipcRenderer.invoke("check-activation"),
  validate: (password) => electron.ipcRenderer.invoke("validate-password", password),
  activate: () => electron.ipcRenderer.invoke("activate-license"),
  getInfo: () => electron.ipcRenderer.invoke("get-activation-info")
});
